/**
 * Author: Jackson D. Poyner
 *
 * Date: 01/09/2026
 *
 * Description: This is a task manager program with non-persistent data that is
 * designed to allow the user to create, view, complete, and delete tasks.
 *
 * Generative AI disclosure: This program does not contain any code that is
 * generated by AI, however I did use a ChatGPT by OpenAI as a tool to come up
 * with a project to practice with, and used it for some debugging for learning
 * purposes because this is a learning program that is not being used in a
 * professional capacity.
 */

#include <algorithm>
#include <iostream>
#include <limits>
#include <string>
#include <vector>

/**
 * This is a task class that will create an object class with a name,
 * description.
 */
class Task {
 public:
  std::string name;
  std::string description;
  bool finishedTask = false;

  Task(std::string n, std::string d, bool f)
      : name(n), description(d), finishedTask(f) {}
};

/**
 * This class will be used to create tasks, and mark tasks as complete.
 */
class TaskManager {
 public:
  // A method for creating new incomplete tasks.
  Task createTask() {
    std::string name;
    std::string description;

    // Clear leftover input
    std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');

    // Prompt the user to enter a new name and description for the task being
    // made.
    while (true) {
      std::cout << "Enter the name of the task: " << "\n";
      std::getline(std::cin, name);

      std::cout << "Enter the description of the task: " << "\n";
      std::getline(std::cin, description);
      if (!name.empty() && !description.empty()) {
        break;
      }
    }
    std::cout << "Successfully created task." << "\n";
    Task task(name, description, false);
    return task;
  }
};

/**
 * This method is the entry point to the homework and the host for all of the
 * functions of the program.
 */
int main() {
  TaskManager taskManager;
  std::vector<Task> tasks;
  int userChoice;

  std::cout
      << "Welcome to my task manager program!" << "\n"
      << "In this program you can create and complete tasks as you please."
      << "\n";

  while (true) {
    std::cout << "What would you like to do?" << "\n";
    std::cout << "0. Create task." << "\n"
              << "1. List tasks." << "\n"
              << "2. Mark a task as complete or incomplete." << "\n"
              << "3. Delete task." << "\n"
              << "4. Quit." << "\n";
    std::cin >> userChoice;

    // Create a new task and add it to the existing vector.
    if (userChoice == 0) {
      tasks.push_back(taskManager.createTask());

    } else if (userChoice == 1) {
      // Checks if the user has created tasks.
      if (tasks.empty()) {
        std::cout << "No tasks available.\n";
        continue;
      }

      int listChoice;

      while (true) {
        std::cout << "How would you like your list to be sorted?" << "\n";
        std::cout << "0. No sort." << "\n"
                  << "1. Incomplete tasks." << "\n"
                  << "2. Complete tasks." << "\n"
                  << "3. Never mind." << "\n";
        std::cin >> listChoice;

        if (listChoice == 0) {
          std::cout << "Tasks: " << std::endl;
          int counter = 0;

          for (const Task& task : tasks) {
            std::cout << counter << ". " << task.name << " " << task.description
                      << " "
                      << " Task complete? "
                      << (task.finishedTask ? "Complete" : "Incomplete")
                      << std::endl;
            counter++;
          }

        } else if (listChoice == 1) {
          std::cout << "Incomplete tasks: " << std::endl;
          int counter = 0;

          for (const Task& task : tasks) {
            if (task.finishedTask == false) {
              std::cout << counter << ". " << task.name << " "
                        << task.description << " "
                        << " Task complete? "
                        << (task.finishedTask ? "Complete" : "Incomplete")
                        << std::endl;
              counter++;
            };
          };
        } else if (listChoice == 2) {
          std::cout << "Complete tasks: " << std::endl;
          int counter = 0;

          for (const Task& task : tasks) {
            if (task.finishedTask == true) {
              std::cout << counter << ". " << task.name << " "
                        << task.description << " "
                        << " Task complete? "
                        << (task.finishedTask ? "Complete" : "Incomplete")
                        << std::endl;
              counter++;
            };
          };
        } else if (listChoice == 3) {
          std::cout << "Exiting task viewer." << "\n";
          break;
        } else {
          std::cout << "Please input a valid choice." << "\n";
        }
      };

    } else if (userChoice == 2) {
      // Checks if the user has created tasks.
      if (tasks.empty()) {
        std::cout << "No tasks available.\n";
        continue;
      }
      int taskChoice;

      while (true) {
        std::cout << "Tasks: " << std::endl;
        int counter = 0;

        for (const Task& task : tasks) {
          std::cout << counter << ". " << task.name << " " << task.description
                    << " "
                    << " Task complete? "
                    << (task.finishedTask ? "Complete" : "Incomplete")
                    << std::endl;
          counter++;
        }
        std::cout << "Select a task that you would like to mark as complete or "
                     "incomplete: "
                  << "\n";
        std::cin >> taskChoice;

        if (taskChoice < 0 || taskChoice >= static_cast<int>(tasks.size())) {
          std::cout << "Please select a task that is contained in the list."
                    << "\n";
        } else {
          Task& currentTask = tasks.at(taskChoice);

          // If the task is incomplete lets set it to complete.
          if (currentTask.finishedTask == false) {
            currentTask.finishedTask = true;
            std::cout << currentTask.name << " is has been set to complete."
                      << "\n";
            break;

            // If the task is complete lets set it to incomplete.
          } else {
            currentTask.finishedTask = false;
            std::cout << currentTask.name << " is has been set to incomplete."
                      << "\n";
            break;
          }
        };
      }

    } else if (userChoice == 3) {
      // Checks if the user has created tasks.
      if (tasks.empty()) {
        std::cout << "No tasks available.\n";
        continue;
      }
      int taskChoice;

      while (true) {
        std::cout << "Tasks: " << std::endl;

        int counter = 0;
        for (const Task& task : tasks) {
          std::cout << counter << ". " << task.name << " " << task.description
                    << " "
                    << " Task complete? "
                    << (task.finishedTask ? "Complete" : "Incomplete")
                    << std::endl;
          counter++;
        }
        std::cout << "Select a task that you would like to mark as complete or "
                     "incomplete: "
                  << "\n";
        std::cin >> taskChoice;

        if (taskChoice < 0 || taskChoice >= static_cast<int>(tasks.size())) {
          std::cout << "Please select a task that is contained in the list."
                    << "\n";
        } else {
          std::cout << tasks.at(taskChoice).name << " erased." << "\n";
          tasks.erase(tasks.begin() + taskChoice);
          break;
        }
      }
    } else if (userChoice == 4) {
      std::cout << "Exiting program." << "\n";
      break;
    } else {
      std::cout << "Please input a valid choice." << "\n";
    }
  };

  return 0;
}